### ISSUE TITLE
Application can't recognize game anymore?

### ISSUE THREAD

**Issue by mettamo** [dragos240/TownManager#4]
Hi, sorry to bother you. I love TownManager and have been using it a lot but since today it doesn't really work anymore. After I created a new town and saved it, I opened TownManager so it would create a backup and i could extract the files. However, suddenly i get an Error message along the lines of "there's no copy of AC:NL in this 3ds", even though it is definitely there.

Thought about just reinstalling Townmanager, but i'm afraid it will overwrite my main town with the new one i just created. 
Thank you for your hard work.

**Comment by mettamo** [comment]
It's a cartridge of acnl and I'm running it on a 2ds with 11.4. Before TownManager shuts itself down it also says "get_titleid failed".

**Comment by JohannesHo** [comment]
Had the same bug this week on my Old 3DS with 11.6 and an digital coppy. 
Got it fixed by renameing the config and the save folder. After relounching Townmanager found my game again and recreated these files. From there I just copied my saves back in the new save directory.

**Comment by dragos240** [comment]
@mettamo Did @JohannesHo's fix fix your bug? I'll look into it either way.

**Comment by horico77** [comment]
Hey! 
I'm having the same issue now. I've tried JohannesHo's solution but it keeps saying the "get_titleid failed" error. I also have a digital copy on 11.6 firmware. I renamed the folder in the root but I only keep getting a folder that has the config file and nothing else

**Comment by noodlynoodlecat** [comment]
i'm a cartridge user, 11.6... i had this issue and followed the solution but it did not work and i looked into my files and lost my save data and it still isnt working.. going to reinstall it at this point since i've nothing to lose anymore, but i hope there's a different solution available?

**Comment by clavzno** [comment]
hey i'm having the problem rn, at first i messed up by creating a new town and then shutting the game off without initial set up because i had to go somewhere, that was when i was on Sys 11.15.0 0-47U, Luma3DS v10.2.1. i lost all my saved towns but that's on me. 

after that i panic deleted and redownloaded ACNL:WA using hshop and updated to Sys 11.17.0-50U, Luma3DS v13.0. still got get_titleid failed. 

finally, i went into the files and deleted the /TownManager/ directory and redownloaded the cia. TownManager asked me if i was using digital or cart so i clicked digital, still nothing.

i have no problem with the lost files i mentioned earlier, just want this to work again. if there's anything i can do let me know :^) thank u for this project

**Comment by dragos240** [comment]
Hey, I should really just archive this project as it's been many years since I last worked on it. Sorry, but I don't really have the time to continue work on this. It may be like this because of the last new leaf update that was released years ago, but I don't know that for sure. Sadly I will be closing this ticket.

**Comment by clavzno** [comment]
it's alright! thank you though
